name: CleanUpCache
on: [workflow_call]

# check this github_token

jobs:
  Clean-Up-Cache:
    name: Clean Up Cache
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Clean up ccahe
        run: |
          echo 'aaa'
          echo 'bbb'

          echo '${{ toJSON(github.event.workflow_run) }}'

          # event
          echo '${{ github.event.workflow_run.event }}'

          # triggering workflow name
          echo '${{ github.event.workflow_run.name }}'

          # PR number
          echo 'xxx${{ github.event.workflow_run.number }}xxx'

          # github.ref
          echo '${{ github.ref }}'
