name: CleanUpCache

on:
  workflow_run:
    workflows: [Clang, Gcc]
    types:
      - completed

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-${{ github.event.workflow_run.name }}
  cancel-in-progress: true

jobs:
  CleanUpCcacheCache:
    name: Clean Up Ccahe Cache for ${{ github.event.workflow_run.name }}
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Clean up ccahe
        run: |
          echo '${{ github.event.workflow_run.event }}'

          # triggering workflow name
          echo '${{ github.event.workflow_run.name }}'

          # github.ref
          echo 'github.ref=${{ github.ref }}'

          gh run download ${{ github.event.workflow_run.id }} -n pr_number
          pr_number=`cat pr_number.txt`
          echo The PR number is $pr_number
