name: CleanUpCache
on: [workflow_call]

# check this github_token

jobs:
  Clean-Up-Cache:
    name: Clean Up Cache
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Clean up ccahe
        run: |
          echo 'aaa'
          echo 'bbb'

          echo '${{ toJSON(github.event.workflow_run) }}'

          # event: push or pull_request
          echo '${{ github.event.workflow_run.event }}'

          # triggering workflow name
          echo '${{ github.event.workflow_run.name }}'

          # refs/heads/main
          echo 'yyy${{ github.ref }}yyy'

          # triggering workflow's PR number
          echo 'zzz${{ github.event.workflow_run.pull_requests[0].number }}zzz'

          echo '${{ toJSON(github.event.workflow_run.pull_requests[0]) }}'
