name: PostClangWorkflow

on:
  workflow_run:
    workflows: [Clang]
    types:
      - completed

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-post-linux-clang
  cancel-in-progress: true

jobs:
  CleanUpCache:
    name: Clean Up Cache for ???
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Clean up ccahe
        run: |
          echo 'aaa'
          echo 'bbb'

          echo '${{ toJSON(github.event.workflow_run) }}'

          # triggering workflow name
          echo `${{ github.event.workflow.name }}

          #
